### ISSUE TITLE
Readme File for usage

### ISSUE THREAD

**Issue by SwaySZ** [janten/dpt-rp1-py#1]
Hi Jan,

Thanks for the great work. Could you please upload a readme file for usage? It doesn't work at my end.

Best,
Sway

**Comment by v217** [comment]
@SwaySZ  I found this:
https://www.mobileread.com/forums/showpost.php?s=fbacf0c7f87211f1b23cf77926552ac4&p=3591405&postcount=6

@janten Thank you this is really great for Linux users!

**Comment by SwaySZ** [comment]
Thanks @v217, but does it work for you?

**Comment by v217** [comment]
@SwaySZ  I get the Sony ereader in one or two months. Until then, I hope so! Please post your experiences and link to it!

**Comment by theopoon** [comment]
Any chance some how to on either how to extract the key.pem or how to ignore it?

Thanks.

**Comment by janten** [comment]
Hey everyone,

the repository now includes a little readme file. I do currently not have enough time to write more detailed instructions but I would gladly accept pull requests.

**Comment by SwaySZ** [comment]
Thank you, @janten 

I am confused about how to set the remote path when uploading a doc. Say, I wanna upload a pdf to the folder 'Note', then I set remote_path = '/folders/Note/test.pdf'. But I got 'Response 404' for the function get_endpoint. I also tried other easy cases, e.g., '/Note/test.pdf'. No success. So please give some details, I'll appreciate it!

Sway

**Comment by janten** [comment]
For some reason the remote root for the DPT-RP1 is _Document/_. Your path should read _Document/Note/test.pdf_.

**Comment by SwaySZ** [comment]
Thanks, @janten  Everything works fine. I prepared a version for Ubuntu 14.04 based on your work.
