### ISSUE TITLE
switch pycrypto to PyCryptodome

### ISSUE THREAD

**Issue by polyval** [janten/dpt-rp1-py#10]
[pycrypto is dead](https://github.com/dlitz/pycrypto/issues/238), and it won't work with Python 3.6 on Windows. I had a rough time trying to install pycrypto, you can use [this httpsig](https://github.com/adpeters/httpsig) which uses PyCryptodome instead of pycrypto. 
It works fine for me.

**Comment by janten** [comment]
Did you already make the required changes and could you create a pull request for this?

**Comment by janten** [comment]
I am closing this issue since it has been fixed in the meantime. Feel free to open it again if the problem persists.
