### ISSUE TITLE
PIP:Please upgrade PIP package.

### ISSUE THREAD

**Issue by Victrid** [janten/dpt-rp1-py#101]
The tool is fantastic and I finally find the way to connect the device using Linux. However, errors same to #89 occured to me when I directly piped the package, and finally fixed by cloning the repo and installing manually, as pull request #95 fixed it nicely, but not synced to pip.

Please upgrade PIP package. Thanks!

P.S. Although many changes have been commited to the repo since October, the version number is still the same with old one hosted on pip. It's suggested that change version number when program changes, as it'll be easier to find where problems hide.

**Comment by janten** [comment]
Thanks for the heads-up, it is indeed time to increase the version number and publish a new release. Do I understand correctly that you tested #95 and it worked well for you? In that case, I will merge that PR and already include it in the new release.

**Comment by Victrid** [comment]
The patch works, at least no duplicate entries occured to me now. File operations can be done sucessfully both under GUI and CLI. But there're still errors prompting. It says something like
```
ERROR:fuse:Uncaught exception from FUSE operation flush, returning errno.EINVAL.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fuse.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/lib/python3.8/site-packages/fuse.py", line 884, in flush
    return self.operations('flush', self._decode_optional_path(path), fh)
  File "/usr/lib/python3.8/site-packages/fuse.py", line 1251, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/lib/python3.8/site-packages/dptrp1/cli/dptmount.py", line 289, in flush
    remote_path = os.path.join(parent.remote_path, fname)
AttributeError: 'Node' object has no attribute 'remote_path'
```
The program continued like nothing happened, and I have no idea on what really went wrong.

**Comment by Victrid** [comment]
The patch works, at least no duplicate entries occured to me now. File operations can be done sucessfully both under GUI and CLI. But there're still errors prompting. It says something like
```
ERROR:fuse:Uncaught exception from FUSE operation flush, returning errno.EINVAL.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fuse.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/lib/python3.8/site-packages/fuse.py", line 884, in flush
    return self.operations('flush', self._decode_optional_path(path), fh)
  File "/usr/lib/python3.8/site-packages/fuse.py", line 1251, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/lib/python3.8/site-packages/dptrp1/cli/dptmount.py", line 289, in flush
    remote_path = os.path.join(parent.remote_path, fname)
AttributeError: 'Node' object has no attribute 'remote_path'
```
The program continued like nothing happened, and I have no idea on what really went wrong.

**Comment by janten** [comment]
The PIP package has been upgraded. Please test again and close this issue if everything works correctly now. The latests version on PyPI is now 0.1.7, while the master branch reflects the version we are currently working on, i.e. 0.1.8.

**Comment by Victrid** [comment]
OK. PIP is updated and everything's right. Thanks a lot!
