### ISSUE TITLE
Changing the port

### ISSUE THREAD

**Issue by peterjohnhartman** [janten/dpt-rp1-py#103]
I apologise if this is obviously stated somewhere, but is it possible to change the port on the DPT RP1 from 8443 to something else (e.g., 443).  On some networks that I use, that port is blocked.  I noticed that in dptrp1.py around line 128 the port gets defined, but I imagine I'd have to change the port on the actual device somehow. 

Thanks in advance, and as always, thanks for the hard work on this project!

**Comment by janten** [comment]
The change would have to be made on the device. I do not think that there is any way to make this change, at least no through any API that I know. You can always run your DPT as an access point and connect your computer to that, which at least spares you the hassle of the USB cable.

**Comment by peterjohnhartman** [comment]
Thanks.
