### ISSUE TITLE
Pop up newly transfered PDF on device

### ISSUE THREAD

**Issue by anasrallah** [janten/dpt-rp1-py#104]
Hello,
do you have a function to show a specific file on the device front screen. Similar to the behavior when printing to device printer.

on another note, do you have the full list of web apis for the device or do you know where to get them?
Thanks

**Comment by janten** [comment]
Hello and sorry for the late reply. This functionality is no indeed supported with the new _show-document_ command. You simply pass the path to a document on the reader and the number of the page you want to display.

```
 dptrp1 show-document "Document/Magazines/Comic.pdf" 5
```
