### ISSUE TITLE
screen sharing

### ISSUE THREAD

**Issue by NittanyLion** [janten/dpt-rp1-py#105]
This is more a feature request than an issue.  The app provides screen sharing.  It would be great if this program could do the same.

**Comment by xpierrohk** [comment]
I've got the same idea and did it at https://github.com/xpierrohk/DigitalPaperApp
I think some with some python knowledge could port the idea fast (https://github.com/xpierrohk/DigitalPaperApp/blob/master/src/main/resources/whiteboard/frontend.html , https://github.com/xpierrohk/DigitalPaperApp/blob/master/src/main/java/net/sony/dpt/ui/html/WhiteboardBackend.java)

Basically you provide an HTTP server with 2 endpoints, one to serve the new screen_shot2 endpoint result and one to serve an html page. The html page will then regularly poll the image and swap. Doing it in html allows you to eventually share the url on the network so you can have many people looking at it on their terminal too, not just like Sony's use case (projection of one screen on the wall)

**Comment by janten** [comment]
Sony's app implements screen sharing using the screenshot feature, which is also available in the command line utility: `dptrp1 screenshot ~/Desktop/test.jpg`. You can simply run this in an endless loop and leave the image open in any fullscreen image viewer to get the basic effect. For better performance, write a small Python script and call [take_screenshot](https://github.com/janten/dpt-rp1-py/blob/d0fcac993377101ae980e668ca3ac970cdc97e77/dptrp1/dptrp1.py#L1063) directly to mitigate the connection and authentication overhead.
