### ISSUE TITLE
Feature Request: Add an option to the "upload" cmd, which crops pdfs to remove extra margins

### ISSUE THREAD

**Issue by kdkalvik** [janten/dpt-rp1-py#114]
Can we get a feature to crop and upload pdf files. When I read any research papers on the tablet, I first crop the pdf file to remove extra margins and then upload it. This makes full use of the available screen space. I use [this](https://gist.github.com/kdkalvik/535ac93a066d5be8154f7121b2738be9) tool to crop my pdfs. It detects the bounding box without margin on every page, calculates the mode of the bounding box across all the pages of a file and then crops the file. It's probably not the best way to do it, but can we get something similar in this tool?

**Comment by janten** [comment]
This is a job for a different tool.
