### ISSUE TITLE
Testing Quaderno FMV-DPP04

### ISSUE THREAD

**Issue by Altitude-Dashboard** [janten/dpt-rp1-py#121]
On macOS Big Sur

pip3 install --user dpt-rp1-py

dptrp1 --addr 192.168.1.59 register
Cleaning up...
<Response [204]>
Requesting PIN...
Encoding nonce...
Please enter the PIN shown on the DPT-RP1: 14710133
Getting certificate from device CA...
<Response [200]>
Generating RSA2048 keys
Device ID: c0bf2e50-3096-4ed4-a850-eac67819bd77
Registering device...
<Response [204]>
Cleaning up...
<Response [204]>

dptrp1 list-documents              
Discovering Digital Paper for 30 seconds…
Failed
Traceback (most recent call last):
  File "/Users/codrut/Library/Python/3.8/bin/dptrp1", line 10, in <module>
    sys.exit(main())
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/dptrp1/cli/dptrp1.py", line 361, in main
    dp.authenticate(client_id, key)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/dptrp1/dptrp1.py", line 350, in authenticate
    nonce = self._get_nonce(client_id)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/dptrp1/dptrp1.py", line 1193, in _get_nonce
    r = self._get_endpoint(f"/auth/nonce/{client_id}")
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/dptrp1/dptrp1.py", line 1181, in _get_endpoint
    return self._endpoint_request("GET", endpoint)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/dptrp1/dptrp1.py", line 1173, in _endpoint_request
    req = requests.Request(method, self.base_url, json=data, files=files)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/dptrp1/dptrp1.py", line 171, in base_url
    return "https://" + self.addr + port
TypeError: can only concatenate str (not "NoneType") to str

**Comment by samdoshi** [comment]
Just a quick note, I don't own a Quaderno, but I am thinking about buying one and so I've been doing a bit of digging.

The Fujitsu Digital Paper PC App is an Elektron based app (I think the Sony one is too?), and if you go delving inside it appears as though it supports many of the same API endpoints e.g. `/system/controls/screen_shot`.

So there is hope that this tool could be made to work with Quadernos too.

**Comment by janten** [comment]
Seems like dpt-rp1-py fails to find your device by hostname. I don't own a Quaderno, but it probably advertises a different Zeroconf-Service than Sony, which uses `_digitalpaper._tcp.local.`. If that is the issue, this command should work fine:

```
dptrp1 --addr 192.168.1.59 list-documents
```

**Comment by Altitude-Dashboard** [comment]
dptrp1 --addr 192.168.1.59 list-documents
Document/Books/The Science of Climbing and Mountaineering.pdf
Document/Books/the-idiot.pdf
Document/Books/Learning Web Design.pdf
Document/Books/Modern Vim.pdf
Document/Books/Practical Vim.pdf
Document/Books/Low-Level Programming.pdf
Document/Books/Introducing Python.pdf
Document/Books/bitcoin.pdf
Document/Books/PDF Explained.pdf
Document/Books/The Secret of Everlasting Life.pdf
Document/Books/Musashi.pdf
Document/Books/S106580GC10_ag.pdf
Document/Books/The Book of Five Rings.pdf
Document/Books/S106581GC10_sg.pdf
Document/Schedule/Scheduler2021.pdf

Thank You! :)

**Comment by Altitude-Dashboard** [comment]
So, if I replace the string _digitalpaper._tcp.local. in dptrp1.py it would work out of the box, the next question is how to determine the Service Name?

**Comment by janten** [comment]
You should be able to see the service name with any DNS-SD-Brwoser. Discovery is a free one for [macOS](https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12) and [iOS](https://apps.apple.com/us/app/discovery-dns-sd-browser/id305441017). If you find the new service Name, let me know and I'll add it to dpt-rp1-py.

**Comment by Altitude-Dashboard** [comment]
dns-sd  -B  _services._dns-sd._udp  local.
Browsing for _services._dns-sd._udp.local.
DATE: ---Thu 04 Mar 2021---
11:31:51.305  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
11:31:51.307  Add        3   1 .                    _tcp.local.          _companion-link
11:31:51.307  Add        3   6 .                    _tcp.local.          _http
11:31:51.307  Add        3   6 .                    _tcp.local.          _companion-link
11:31:51.307  Add        3   6 .                    _tcp.local.          _airplay
11:31:51.307  Add        3   6 .                    _tcp.local.          _hap
11:31:51.307  Add        3   6 .                    _tcp.local.          _wifiman-local-speedtest
11:31:51.307  Add        3   6 .                    _tcp.local.          _airdrop
11:31:51.307  Add        3   6 .                    _tcp.local.          _dp_fujitsu
11:31:51.307  Add        2   6 .                    _tcp.local.          _spotify-connect
^C

Seems like the name is: _dp_fujitsu

**Comment by Altitude-Dashboard** [comment]
I am on a Mac, and I installed dptrp1 using --user option so I have edited:

~/Library/Python/3.8/lib/python/site-packages/dptrp1/dptrp1.py

and changed line 126 to look like:

        ServiceBrowser(zc, "_dp_fujitsu._tcp.local.", self)

and now it works.

Thank You!

**Comment by janten** [comment]
Included in v0.1.11
