### ISSUE TITLE
update due to changes in zeroconf

### ISSUE THREAD

**Issue by kayleachampion** [janten/dpt-rp1-py#126]
I've started getting warnings from zeroconf when I run dptrp1 on the command line -- here's the message: 

`Discovering Digital Paper for 30 seconds…
~/.local/lib/python3.8/site-packages/zeroconf/_services/browser.py:169: FutureWarning: <dptrp1.dptrp1.LookUpDPT object at 0x7fc5942fd5e0> has no update_service method. Provide one (it can be empty if you don't care about the updates), it'll become mandatory.`

**Comment by vico** [comment]
This is resolved with [this](https://github.com/janten/dpt-rp1-py/pull/131) PR.
