### ISSUE TITLE
Unable to register the device

### ISSUE THREAD

**Issue by x-ji** [janten/dpt-rp1-py#16]
System: Ubuntu 16.04 LTS
Python: 3.5.2

When I try to register the device with `dptrp1 --client-id deviceid.dat --key privatekey.dat --addr 10.0.0.8 register`, I get the following error:

```
Cleaning up...
<Response [204]>
Requesting PIN...
<Response [200]>
Encoding nonce...
<Response [403]>
Traceback (most recent call last):
  File "/usr/local/bin/dptrp1", line 118, in <module>
    _, key, device_id = dp.register()
  File "/usr/local/lib/python3.5/dist-packages/dptrp1/dptrp1.py", line 107, in register
    if(base64.b64decode(m3['a']) != n2):
KeyError: 'a'
```

Any idea what happened here?

I'm sure my computer and the device are both connected to the same WiFi network.

**Comment by x-ji** [comment]
For some reason when I tried again today it worked.

**Comment by BryceStevenWilley** [comment]
I'm running into the same issue.  Same system and python version as x-ji above. 

Curiously, Requesting PIN shows up on the computer, but no PIN is ever requested on the device. Note that the device is already registered with another Ubuntu machine; do you need a different client_id and key.pem for each computer? In that case, I'm not sure how to generate different keys.

Both the computer and the dpt are connected to a WPA2-PSK wifi network, device is showing signal strength as 'good'.

**Comment by wangyiqiu** [comment]
Ran into the same issue, went fine after a few tries. So keep trying.
