### ISSUE TITLE
Question regarding the remote path in upload

### ISSUE THREAD

**Issue by stokhos** [janten/dpt-rp1-py#21]
Hi:

I tried to upload several books to my dpt-rp1. But I had problem with remote path.

In my dpt-rp1, I have folder Document to store my pdf files.
I tried this:

dptrp1 --client-id deviceid.dat --key privatekey.dat --addr 192.168.1.28 upload Convex_optimization.pdf /Document

But I got an error saying something is wrong with entry_id.

Could you help me fix this problem?

Best

**Comment by YLiLarry** [comment]
Try `dptrp1 --client-id deviceid.dat --key privatekey.dat --addr 192.168.1.28 upload Convex_optimization.pdf Document/` instead.

**Comment by stokhos** [comment]
@YLiLarry Thank you very much! BTW do you know how to find the Bluetooth address?

Best

**Comment by YLiLarry** [comment]
I didn't even need to put the address for mine to work. Do you have multiple DPT-RP1s? 
Finding bluetooth address may be OS specific. What operations system are you on?
On MacOS I just use click bluetooth on the top bar with `Option` key pressed down. And the IP address is shown under each device.

**Comment by stokhos** [comment]
I have one as well.  My computer is running linux, it works fine, but i'm worried it may not work on other computer. Thank you very much and I appreciate your reply.
