### ISSUE TITLE
How did you find out these APIs?

### ISSUE THREAD

**Issue by YLiLarry** [janten/dpt-rp1-py#22]
Hi janten thank you very much for working on this wonderful project.
I wonder how did you find out the APIs such as `/system/configs/wifi_accesspoints` or `/documents2`, etc.
Is there a tool to sniff it?

**Comment by janten** [comment]
Sony's Digital Paper App is an Electron application which makes it pretty straightforward to look for API endpoints in the source code. This is how I found the original set of APIs, which already covered most of the basic interaction with the device. Someone added a JSON file with additional endpoints later on, I don't know where he got that.

**Comment by janten** [comment]
I will close this issue now, feel free to re-open it if any questions remain.
