### ISSUE TITLE
can you add license?

### ISSUE THREAD

**Issue by askalski** [janten/dpt-rp1-py#24]
Hi,

can you add license file? I would like to fork and add FUSE interface, but I am employee of large corp and I need a clearance to proceed. Without license on your code I am not sure about their answer.

Kindest Regards

**Comment by askalski** [comment]
@janten hi, could you give it a look? Anything like Apache, MIT, BSD should work.

**Comment by janten** [comment]
Hi @askalski,

you may use my code under the MIT license but I guess I cannot give you a license for the code that has been merged through pull requests. Since this is now the largest part of the code in the repository, I will not add a license unless everyone agrees on one.

**Comment by askalski** [comment]
OK, so can you make a query? Miracles happen in the Internet, maybe contributors will just agree.

**Comment by askalski** [comment]
@bpteague @farhaven , would you agree on MIT license to your contributions?

**Comment by bpteague** [comment]
You may use my code under an MIT license.  Also, I've got another contribution (a GUI!) -- lemme send a pull request.

**Comment by bpteague** [comment]
Ah, there has been some divergence.  It may be a little bit until I get around to merging.  In any case, if you'd like to check out a basic GUI, have a look at 933ce7bfa2a3ad1033e2887c1b9e97c9d44ba842 (-:

**Comment by askalski** [comment]
that's so cool. One person more, and I go with FUSE, maybe automount.

**Comment by pi8027** [comment]
Now I'm preparing some pull requests, and I think that the MIT license is good for this software.
However, if endpoints.json was retrieved from DPT-RP1 or Digital Paper App, it probably should be deleted.

**Comment by farhaven** [comment]
Sorry for taking this long to reply. I'm fine with MIT.

**Comment by askalski** [comment]
@janten 
It seems like all current and one future contributors are fine with MIT. Could you push it?
