### ISSUE TITLE
Question about sync and original app

### ISSUE THREAD

**Issue by ghostwheel** [janten/dpt-rp1-py#34]
It is very nice that the full source to the sony app is available.
However, on the mac the app is quite horrible.

So I wanted to ask:
1. How difficult would it be to implement syncing?
Is there a way to see changed files? Modification times on files? 

2. Could we maybe collect information on the sony app? What have you already figured out?
For example, I understand it works with a database on the computer side. 
Where is that database? Or is the whole database on the rp1?
Did you find ways to insert small debugging dialogs/printouts into the program?
I guess it is possible to debug with console.log()

Currently something is wrong with my sync - it finishes quite quickly, but then gets stuck forever and eventually returns with an error 17-0000-0000. 

Oh, I found the database. On the mac.
It is 
`~/Library/Application Support/Sony Corporation/Digital Paper App/sqlite3.db`

This database has 2 tables: `file_stamp`, `sync_folder_pair`
 
`sync_folder_pair` simply has a list of the synced folders.

`file_stamp` is more interesting. Its columns are
`syncId`, `localFolderPath`, `localFileName`, `localStamp`, `remoteFolderPath`, `remoteFileName`, `remoteStamp`.

All pretty self-explanatory. Except for `localStamp` and `remoteStamp`. They are not identical.
`localStamp` looks like: `bdba629e0f11b377f48759184ebf0aac`, and `remoteStamp` looks like `b5ea42e3b838.1.0` (this is for the same file). I'll try to dig deeper to see how they are used, and how the database is updated.

**Comment by janten** [comment]
The tool now has a basic `sync` command, which uses only the timestamp. A more robust implementation could also track deletions or concurrent changes on both the computer and the reader. If you feel up to the task, a pull request would be appreciated.

**Comment by huntersnyder** [comment]
Great to see it. I will trial this feature from Friday. Anyone who has insights on a more robust means of tracking/merging concurrent changes, please consider pulling.

Cheers,

H


On 09 Jul, 2019, at 19:37, Jan-Gerd Tenberge <notifications@github.com<mailto:notifications@github.com>> wrote:


The tool now has a basic sync command, which uses only the timestamp. A more robust implementation could also track deletions or concurrent changes on both the computer and the reader. If you feel up to the task, a pull request would be appreciated.
