### ISSUE TITLE
Subpath issue

### ISSUE THREAD

**Issue by MzXuan** [janten/dpt-rp1-py#39]
Hello, thanks for the script!

I have tested it on Ubuntu with IPv6. All the operations with only one path are working fine (e.g. upload documents to Document/... ; List documents; create new folder under Document/...)

However, all the operations requiring a subpath does not work (Includeing download file, delete file, create subfolder). 

For example:
`dptrp1 --client-id ~/deviceid.dat --key ~/privatekey.dat --addr [f
e80::xxxx:xxxx:xxxx:xxxx%enp0s20u1] new-folder Document/test` <- this works.

`sudo dptrp1 --client-id ~/deviceid.dat --key ~/privatekey.dat --addr [f
e80::xxxx:xxxx:xxxx:xxxx%enp0s20u1] new-folder Document/test/test  ` <-this does not work

I have checked the URL before sending the request, for the operations with subfolders, "/" is encoded to "%2F".  But I still can not figuer the issue out. 

The error is:
> req:  <Response [404]>
Error: 40401   The designated resource was not found.
status: 404
Traceback (most recent call last):
  File "/usr/local/bin/dptrp1", line 4, in <module>
    __import__('pkg_resources').run_script('dpt-rp1-py==0.1.0', 'dptrp1')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/dpt_rp1_py-0.1.0-py3.5.egg/EGG-INFO/scripts/dptrp1", line 142, i
n <module>
    commands[args.command](dp, *args.command_args)
  File "/usr/local/lib/python3.5/dist-packages/dpt_rp1_py-0.1.0-py3.5.egg/EGG-INFO/scripts/dptrp1", line 41, in
 do_new_folder
    d.new_folder(remote_path)
  File "/usr/local/lib/python3.5/dist-packages/dpt_rp1_py-0.1.0-py3.5.egg/dptrp1/dptrp1.py", line 272, in new_f
older
    directory_id = self._resolve_object_by_path(remote_directory).json()['entry_id']
KeyError: 'entry_id'

Anyone could help? Thanks.

**Comment by BryceStevenWilley** [comment]
I can confirm this exists, I just ran into the same issue. Strangely enough, I never had this issue when connecting over wi-fi, even though the USB connection is much faster and more reliable.

**Comment by cristobaltapia** [comment]
This problem appears to still be present. It has nothing to do with the presence of "Document" in the path, since I have that already. Over WiFi it works perfectly fine.
