### ISSUE TITLE
Issue on delete folder

### ISSUE THREAD

**Issue by TracebackS** [janten/dpt-rp1-py#50]
Hi:
      Thanks for your wonderful project, it helps me a lot. However, there is something wrong when I try to delete a remote subfolder: it just keeps silent just like nothing was wrong,  but nothing happens with my device.
      There is nothing wrong with list documents or upload files, I can even create new folder on my device, so I did use  it in a right way.
      I do these on linux OS, connect my device with wifi, register it successfully. Can anybody give me some suggestions?
     Thanks a lot!

**Comment by dawag** [comment]
I don't think that something is wrong in the code, it just seems that there isn't a possibility for deleting folders yet - only deleting files. However I also think that this missing option is an big issue, how could it be resolved then?

**Comment by janten** [comment]
Deleting folders should now be possible. Feel free to re-open this issue if it does not work for you.
