### ISSUE TITLE
httpsig made Signer.sign public

### ISSUE THREAD

**Issue by WindProphet** [janten/dpt-rp1-py#54]
When I run this program, it meets this problem
```
File "dptrp1.py", line 214, in authenticate
    signed_nonce = sig_maker._sign(nonce)
AttributeError: 'Signer' object has no attribute '_sign'
```

httpsig module made `Signer.sign` method public, so the method `_sign` should be replaced by `sign`

https://github.com/ahknight/httpsig/commit/60dbb7b0b43b922c1aba0b23705abf38f1a7afd7

```python
signed_nonce = sig_maker.sign(nonce)
```

**Comment by janten** [comment]
This should be fixed by #56.
