### ISSUE TITLE
Access over USB failing if https_proxy environment variable set

### ISSUE THREAD

**Issue by cuihtlauac** [janten/dpt-rp1-py#55]
Step to reproduce.

1. Get a machine behind a proxy (this might be the easiest or hardest point)
2. Disable Wi-Fi on the DPT-RP1
3. Connect the DPT-RP1 using a USB cable
4. Set the connection to CDC-ECM. I'm doing: printf "\x01\x00\x00\x01\x00\x00\x00\x01\x01\x04" > /dev/ttyACM0
5. Find the DPT-RP1 IPv6 address. I'm doing:  avahi-resolve -n digitalpaper.local
6. Find the DPT-RP1 network interface name. I'm using ifconfig
7. Try to get the list of the documents. It fails
python3 bin/dptrp1 --addr "[fe80::xxxx:xxxx:xxxx:xxxx%enp0s20u4u1]" --client-id ... --key ... list-documents
8. Unset the https_proxy variable
9. Retry. It works.

Most probably related with urllib3/requests.

**Comment by ampolloreno** [comment]
@cuihtlauac Did you figure out anything else about this? I'm running into the same issue.

**Comment by janten** [comment]
This seems to be expected behavior to me. You could use an additional [no_proxy environment](https://unix.stackexchange.com/questions/23452/set-a-network-range-in-the-no-proxy-environment-variable) variable to exclude your DPT-RP1 from the proxy settings.
