### ISSUE TITLE
USB Ethernet Fails

### ISSUE THREAD

**Issue by xyttyxy** [janten/dpt-rp1-py#57]
Trying to register on linux(Ubuntu 18.04 LTS, KDE). I followed the guide to feed a byte sequence by this command:
I got IPv6 address just fine:
Ethernet:
`be:a7:89:f5:55:c3`
IPv6(link-local):
`fe80::244f:46ff:fe5c:cbe9`
IPv6(w/ scope identifier):
`fe80::244f:46ff:fe5c:cbe9%enp0s20f0u11`
(I noticed ifconfig has a different address?)
Final URI:
`https://[fe80::244f:46ff:fe5c:cbe9%enp0s20f0u11]:8443/...`
(what is this 8843?)
But what's the syntax to actually register? ALL I've tried gives me timeed out error from urllib.

**Comment by janten** [comment]
It's been 9 months since you opened this issue, but the newest version of the _dptrp1_ command no longer needs the _--addr_ option to find your device. Simply run `dptrp1 register`.
