### ISSUE TITLE
deviceid.dat

### ISSUE THREAD

**Issue by ghost** [janten/dpt-rp1-py#64]
xxxxx@DESKTOP-QV2HMLF MINGW64 /c/dpt-rp1-py-master
$ dptrp1 --client-id deviceid.dat --key privatekey.dat --addr 172.30.1.8 list-documents
Traceback (most recent call last):
File "C:/Users/gkhs1/AppData/Local/Programs/Python/Python37/Scripts/dptrp1", line 161, in 
with open(args.client_id) as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'deviceid.dat'

What should i do????

**Comment by yunjae2** [comment]
Have you created `device.dat` using `register` command?

**Comment by hyunky** [comment]
Not yet 
Shoud i register first???

**Comment by yunjae2** [comment]
Yes you should.
http://jstvz.org/posts/dptrp1-sync/
This post would be a help.

**Comment by hyunky** [comment]
Should I unblock the firewall when i register??
