### ISSUE TITLE
Document date

### ISSUE THREAD

**Issue by phsamuel** [janten/dpt-rp1-py#65]
Is it possible to extract the document date without downloading it?

**Comment by yunjae2** [comment]
I added the feature in [my fork repository](https://github.com/yunjae2/dpt-rp1-py). Use `document-info` as command argument for extracting document informations.

**Comment by janten** [comment]
@yunjae2 would you mind rebasing your fork and submitting a pull request? Thanks ahead.

**Comment by yunjae2** [comment]
Sure.
