### ISSUE TITLE
Issues with firmware 1.6.00.15110

### ISSUE THREAD

**Issue by cuihtlauac** [janten/dpt-rp1-py#66]
I'm experiencing issues since I've updated to 1.6.00.15110. Frequently, communication fails. I have to either turn Wi-Fi off and on or reboot in order to be able to establish successful communication. Once working, it seems that uploading a file leaves something in a dirty state since communication is broken once again.

**Comment by cristobaltapia** [comment]
The firmware 1.6 has been removed, because of serious bugs [1]. So I guess you will have to wait until they release the new fixed version.

[1] https://www.mobileread.com/forums/showthread.php?t=320790

**Comment by janten** [comment]
I am going to close this issue since it does not seem to be a problem with this script. Feel free to re-open it if you think otherwise.
