### ISSUE TITLE
Sync is unidirectional

### ISSUE THREAD

**Issue by Marathon2112** [janten/dpt-rp1-py#71]
Running the `sync` command only syncs files from the DPT-RP1 to the computer (and not the converse).
For example, I have a subfolder on my computer whose contents are not uploaded to the same, empty folder on the DPT-RP1.

Using v1.6 (although I do not think this is relevant).

**Comment by janten** [comment]
Can you please try again with the new version?

**Comment by Marathon2112** [comment]
Works like a charm! Thanks!

**Comment by Marathon2112** [comment]
Actually, timestamps of new documents uploaded to the device seem to be set to the creation time (and not the computer time). Thus a second run of the `sync` command downloads the files back to the computer if the DPT-RP1 time is later than the computer time.
