### ISSUE TITLE
Missing authors information in setup.py

### ISSUE THREAD

**Issue by janten** [janten/dpt-rp1-py#76]
I have published [dpt-rp1-py on pypi](https://pypi.org/project/dpt-rp1-py/), which reads the author information from the _setup.json_ file, which currently only lists me as the sole author. Everyone who contributed to this repository is invited to add their name to the file, too. This includes all of the authors of merged pull requests: @alex-fu27, @bpteague, @chrigro, @cuihtlauac, @cvcore, @cycomanic, @HappyZ, @jgrigera, @Nymphium, @pi8027, @qintang, @sree314, @x-ji, @yunjae2, and @ztuowen.

**Comment by jgrigera** [comment]
That is very generous @janten. Will do

**Comment by pi8027** [comment]
I agree with this. So should we provide contact information here, like this?:
`"Kazuhiko Sakaguchi" <pi8027@gmail.com>`

**Comment by HappyZ** [comment]
thanks, please help add `Yanzi Zhu` with email `zhuyanzi at gmail dot com` :D

**Comment by yunjae2** [comment]
I added @pi8027 , @HappyZ in my [PR](https://github.com/janten/dpt-rp1-py/pull/79#issue-314772562]) :).

**Comment by cycomanic** [comment]
I've created a new pull request with my info, thanks for including us
