### ISSUE TITLE
KeyError: 'TRAVIS_TAG'

### ISSUE THREAD

**Issue by peterjohnhartman** [janten/dpt-rp1-py#80]
Hi, 

First time user -- noticed you had changes from yesterday, so maybe this is already a known problem.  Happy to supply more information (Archlinux, running python3):

I get this error when I run pip install dpt-rp1-py:

peterjh@auriol ~/src/dpt-rp1-py-0.1.1 $ pip install dpt-rp1-py
Collecting dpt-rp1-py
  Using cached https://files.pythonhosted.org/packages/0f/c8/56745214b09d9812a528126a1d6560b222883e1e8b60419effdf93a100b8/dpt-rp1-py-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    ! Error loading setup.json file in the same directory as setup.py.
      Check your installation.
      Exception: [Errno 2] No such file or directory: '/tmp/pip-install-d1wd3zy5/dpt-rp1-py/setup.json'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-d1wd3zy5/dpt-rp1-py/

I get this error when I try to compile it:

peterjh@auriol ~/src/dpt-rp1-py-0.1.1 $ pip3 install .
Processing /home/peterjh/docs/src/dpt-rp1-py-0.1.1
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-cqpg7swb/setup.py", line 44, in <module>
        version=os.environ['TRAVIS_TAG'].replace("v", ""),
      File "/usr/lib/python3.7/os.py", line 678, in __getitem__
        raise KeyError(key) from None
    KeyError: 'TRAVIS_TAG'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-cqpg7swb/

**Comment by janten** [comment]
Should be fixed now, please try again with `pip install --upgrade dpt-rp1-py`. If you use python3, you may need to use `pip3` instead of `pip`. You do not need to download the project for this, it should work out of the box and install any requirements automatically.

**Comment by peterjohnhartman** [comment]
Works like a champ now, thanks!
