### ISSUE TITLE
Issue getting Ethernet-over-USB working

### ISSUE THREAD

**Issue by peterjohnhartman** [janten/dpt-rp1-py#83]
Hi, 

First things first, thanks so much for this python script!  I've got a headscratcher.  I followed the documents in "docs" https://github.com/janten/dpt-rp1-py/blob/master/docs/linux-ethernet-over-usb.md for getting ethernet-over-usb working.  I managed to send the serial command for cdc/ecm mode, and set up Network Manager to assign it a local ip.  Hence, avahi-resolve -n digitalpaper.local gives me a legit ipv6:

fe80::90df:46ff:fe5c:c471

According to ifconfig my DPTRP1 is:

enp0s20f0u1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.217.149  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::7c07:fd10:f9b5:c4f0  prefixlen 64  scopeid 0x20<link>
        ether 72:c4:5c:46:df:93  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 878 (878.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0

However, I'm stumped on the next step.  I've tried various combinations in --addr argument for dptrpt1 but I get errors, e.g.: err.txt output when I try

peterjh@auriol ~ $ dptrp1 --addr "[fe80::90df:46ff:fe5c:c471%enp0s20f0u1]" list-folders 2> err.txt

I tried various other combinations, but much the same.  Thanks in advance!
[err.txt](https://github.com/janten/dpt-rp1-py/files/3602029/err.txt)

**Comment by janten** [comment]
Do you get the same error if you run just `dptrp1 register` with no other arguments?

**Comment by peterjohnhartman** [comment]
I should note that the ipv6 that ifconfig reports is different than the ipv6 that avahi-resolv -n digitalpaper.local reports.

peterjh@auriol ~/.local/bin $ avahi-resolve -n digitalpaper.local
digitalpaper.local      fe80::90df:46ff:fe5c:c471

ifconfig
enp0s20f0u1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.217.149  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::7c07:fd10:f9b5:c4f0  prefixlen 64  scopeid 0x20<link>
        ether 72:c4:5c:46:df:93  txqueuelen 1000  (Ethernet)
        RX packets 20  bytes 4287 (4.1 KiB)

However, I tried both and get the same error.

**Comment by janten** [comment]
The address displayed in `ifconfig` is the address of your computer's network interface, you need the one from `avahi-resolve`.

Looks like the requests library interprets the IPv6 address as a hostname, this may be because of the network path identifier, which should not be needed. Try to use just

```
dptrp1 --addr fe80::90df:46ff:fe5c:c471 register
```

But for me the most reliable method so far was to disable WiFi on the DPT-RP1 device, then run `dptrp1 register` with no further arguments, and switch WiFi on while `dptrp1` is searching for the device.

**Comment by Marathon2112** [comment]
Is there a way to keep the device permanently in RNDIS mode? I need to run pyserial each time it's connected over USB.

**Comment by peterjohnhartman** [comment]
closing this; the problem was on my end.

**Comment by Marathon2112** [comment]
@peterjohnhartman Any details on what was the issue? I've still having trouble getting Ethernet-over-USB working.
